language: node_js
node_js:
- 6.4.1
addons:
  ssh_known_hosts: domonicmilesi.com
before_install:
- bash _scripts/before_install.sh
script:
- bash _scripts/build.sh
after_success:
- bash _scripts/deploy.sh
